CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n

# BLE Profile Names (max 4 characters recommended, empty = hidden)
CONFIG_NICE_VIEW_BLE_PROFILE_0_NAME="homewin"
CONFIG_NICE_VIEW_BLE_PROFILE_1_NAME="ipad"
CONFIG_NICE_VIEW_BLE_PROFILE_2_NAME="notewin"
CONFIG_NICE_VIEW_BLE_PROFILE_3_NAME="etc"
CONFIG_NICE_VIEW_BLE_PROFILE_4_NAME="homemac"